#!/bin/sh
set -eu

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
SAMPLES="${1:-128}"
SIZE="${2:-512}"
OUTPUT_DIR="${3:-Examples/Renders/Materials}"
PRESET_FILTER="${4:-${MATERIAL_PRESET:-}}"

SCENE="Examples/SceneScripts/MaterialTestBall/material-testball.denrim"
PREVIEW_INCLUDE="Examples/SceneScripts/MaterialTestBall/preview-material.denrim"
PRESET_SOURCE="Sources/DenrimRendererKit/Scene/BuiltInMaterialLibrary.swift"
RENDERER=".build/release/denrim-render-preview"

cd "$ROOT_DIR"
mkdir -p "$OUTPUT_DIR"

if [ ! -f "$SCENE" ]; then
    echo "Material test ball scene not found: $SCENE" >&2
    exit 1
fi

if [ ! -f "$PREVIEW_INCLUDE" ]; then
    echo "Material preview include not found: $PREVIEW_INCLUDE" >&2
    exit 1
fi

PRESETS="$(awk '
    /public static let presets:/ {
        inPresetsArray = 1
        next
    }
    inPresetsArray && /public static var identifiers:/ {
        exit
    }
    inPresetsArray && /^[[:space:]]*preset\(/ {
        inPreset = 1
        next
    }
    inPresetsArray && inPreset && match($0, /^[[:space:]]*"[^"]+"/) {
        line = substr($0, RSTART, RLENGTH)
        gsub(/^[[:space:]]*"/, "", line)
        gsub(/"$/, "", line)
        print line
        inPreset = 0
    }
' "$PRESET_SOURCE")"

if [ -z "$PRESETS" ]; then
    echo "No built-in material presets found in $PRESET_SOURCE." >&2
    exit 1
fi

if [ -n "$PRESET_FILTER" ]; then
    if ! printf '%s\n' "$PRESETS" | grep -Fxq "$PRESET_FILTER"; then
        echo "Unknown built-in material preset: $PRESET_FILTER" >&2
        echo "Available presets:" >&2
        printf '  %s\n' $PRESETS >&2
        exit 1
    fi
    PRESETS="$PRESET_FILTER"
fi

BACKUP_INCLUDE="$(mktemp "${TMPDIR:-/tmp}/denrim-preview-material.XXXXXX")"
cp "$PREVIEW_INCLUDE" "$BACKUP_INCLUDE"

cleanup() {
    if [ -f "$BACKUP_INCLUDE" ]; then
        cp "$BACKUP_INCLUDE" "$PREVIEW_INCLUDE"
        rm -f "$BACKUP_INCLUDE"
    fi
}

interrupt() {
    cleanup
    trap - EXIT HUP INT TERM
    exit 130
}

trap cleanup EXIT
trap interrupt HUP INT TERM

swift build -c release --product denrim-render-preview

printf '%s\n' "$PRESETS" | while IFS= read -r preset; do
    [ -n "$preset" ] || continue
    output="$OUTPUT_DIR/$preset.png"

    {
        printf '# Generated by Examples/Tools/render-built-in-materials.sh\n'
        printf 'material PreviewMaterial preset %s\n' "$preset"
    } > "$PREVIEW_INCLUDE"

    echo "Rendering $preset -> $output"
    "$RENDERER" "$output" "$SAMPLES" "$SIZE" script beauty "$SCENE"
done
